<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Test script is fail]]>
    </line>
  </reporter-output>
  <suite started-at="2025-05-01T14:27:02 IST" name="Default suite" finished-at="2025-05-01T14:27:07 IST" duration-ms="5355">
    <groups>
    </groups>
    <test started-at="2025-05-01T14:27:02 IST" name="Default test" finished-at="2025-05-01T14:27:07 IST" duration-ms="5355">
      <class name="listenner.Testscript">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:listenner.Testscript@37afeb11]" started-at="2025-05-01T14:27:02 IST" name="openBrowser" finished-at="2025-05-01T14:27:06 IST" duration-ms="4180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="login()[pri:0, instance:listenner.Testscript@37afeb11]" started-at="2025-05-01T14:27:06 IST" name="login" finished-at="2025-05-01T14:27:07 IST" duration-ms="1059" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Home page is not displayed expected [Demo Web Shop] but found [Demo Web Shop. Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Home page is not displayed expected [Demo Web Shop] but found [Demo Web Shop. Login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at listenner.Testscript.login(Testscript.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test script is fail]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- listenner.Testscript -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
